### ISSUE TITLE
Fail to deploy to Heroku

### ISSUE THREAD

**Issue by minhduc19** [moneil/OSCELOT-DSKTOOL-for-HEROKU#11]
Hi, 

I tried to build this app on both Heroku and my local computer but it fails. Here is the error I had:

       The conflict is caused by:
           The user requested websockets==9.1
           pyppeteer 0.2.2 depends on websockets<9.0 and >=8.1

Could you please adjust the requirement file?

Thank you

**Comment by moneil** [comment]
Done. Builds locally on my laptop.

Cheers,
-m

Mark O’Neil (he/him/his)
Director, Product Management, Platform and APIs
1-603-287-1836

Blackboard is now part of Anthology<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.blackboard.com%2Fanthology&data=04%7C01%7CKylie.Johnson%40blackboard.com%7Cc78823d7692345dd188208d99e6a423e%7Cbf0b29a25e5c4aaaba4dac988df15ea6%7C0%7C0%7C637715001485830077%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9%2Fhu520AaLKUQlzw1tZvo5tkQuzItMFYXmKRZIEGqyc%3D&reserved=0>
Quick Links:
Developer AMI<https://aws.amazon.com/marketplace/seller-profile?id=f6f7de05-e6d2-47f8-96e8-51cc4b38182b>
Developer Program<https://developer.blackboard.com/>
Developer Documentation<https://docs.blackboard.com/>
Join Blackboard Techies Slack Channel!<https://join.slack.com/t/blackboardtechies/shared_invite/zt-nheykjth-wLgONrE58MS53H~oySYk1g>


Please do not feel obligated to respond outside your normal business hours. Thank you.

From: dory ***@***.***>
Reply-To: moneil/OSCELOT-DSKTOOL-for-HEROKU ***@***.***>
Date: Friday, January 21, 2022 at 10:10 AM
To: moneil/OSCELOT-DSKTOOL-for-HEROKU ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [moneil/OSCELOT-DSKTOOL-for-HEROKU] Fail to deploy to Heroku (Issue #11)


Hi,

I tried to build this app on both Heroku and my local computer but it fails. Here is the error I had:

   The conflict is caused by:

       The user requested websockets==9.1

       pyppeteer 0.2.2 depends on websockets<9.0 and >=8.1

Could you please adjust the requirement file?

Thank you

—
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmoneil%2FOSCELOT-DSKTOOL-for-HEROKU%2Fissues%2F11&data=04%7C01%7Cmark.oneil%40blackboard.com%7C40b19e23cc7e47e283b308d9dcf0366e%7Cbf0b29a25e5c4aaaba4dac988df15ea6%7C0%7C0%7C637783746524442775%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6BuF14MsRQiHh9g0C3DrqGJgBId84CSpbdh%2BoXHsSAs%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABJGN5NPE2DCH54HAFFWP73UXFZPVANCNFSM5MPYNZWA&data=04%7C01%7Cmark.oneil%40blackboard.com%7C40b19e23cc7e47e283b308d9dcf0366e%7Cbf0b29a25e5c4aaaba4dac988df15ea6%7C0%7C0%7C637783746524442775%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yiYRnGQp81mmZQQtmoLLnKmsjmRwZ2EnVAjwpkxfgC8%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

This email and any attachments may contain confidential and proprietary information of Blackboard that is for the sole use of the intended recipient. If you are not the intended recipient, disclosure, copying, re-distribution or other use of any of this information is strictly prohibited. Please immediately notify the sender and delete this transmission if you received this email in error.
